### ISSUE TITLE
Suggestion: use class module rather than period-delimiting classes

### ISSUE THREAD

**Issue by axefrog** [yelouafi/snabbdom-jsx#4]
Looking in the snabbdom-jsx code, it looks like you're taking the values in a `classNames` array and translating that to a period-delimited class list to be appended to the element name. Snabbdom (I assume incorrectly) interprets this as needing to create a new element, which causes problems elsewhere. Is there a way you can use the snabbdom class module instead? I'm guessing that it would alleviate this problem.

**Comment by yelouafi** [comment]
>Looking in the snabbdom-jsx code, it looks like you're taking the values in a classNames array and translating that to a period-delimited class list to be appended to the element name

the code just build the `sel` attribute of virtual nodes.  the expression `<div classNames="c1 c2" ..>` is the equivalent of `h('div.c1.c2', ...)` where `div.c1.c2` is the `sel` attribute.

>Snabbdom (I assume incorrectly) interprets this as needing to create a new element, which causes problems elsewhere

I'm not sure i understand the issue; if i'm not mistaken Snabbdom creates an element only if it encounters a new vnode; this happens either on the top level node the first time the `patch` method is invoked [Here](https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L215-L217) or when updating the children of an existing vnode [here](https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L160-L163) and [here](https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L197-L198)

**Comment by axefrog** [comment]
My testing today confirmed that appending an extra class via `classNames` caused the element to be destroyed and recreated by snabbdom. I've reported this as an issue; hopefully they'll fix it. Even so, I would imagine that parsing classes from a string, rather than looking at the class module object is probably less efficient.

**Comment by yelouafi** [comment]
Normally the `sel` attribute should not change as it's used by snabbdom to compare the old and the new vnodes. the classNames array is merely a facility to build the `sel` attrbute. Dynamic classes should be specified instead via a module like the class module.

I could imagine using `class` module with an object whose keys are the array elements and values set to `true`; i.e. instead of `classNames={['c1', 'c2' ...]}` you can have `class={{c1:true, c2: true, ...}}`; But looking at [the code of the class module](https://github.com/paldepind/snabbdom/blob/master/modules/class.js) the code iterates only on the new object, so if the old object contains keys  (=class names) that are not present in the new one they will not be modified; this means that for dynamic arrays new classes will be added but deleted classes will not be removed from the element classList. 
A possible solution is to improve on the `class` module to handle dynamic arrays as well (in addition to objects); i'm looking for @paldepind comments on the paldepind/snabbdom#36 issue

**Comment by axefrog** [comment]
Sure, and I agree- you may as well leave this one hanging until @paldepind comes back with his thoughts on that issue.
